name: Update Contributions File

on:
  schedule:
    # Run every day at 12 AM EST (5 AM UTC)
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  update-contributions:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Generate contributions markdown
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p docs
          node .github/scripts/generate-contributions.js

      - name: Check for changes
        id: git_diff
        run: |
          if git diff --quiet docs/contributions.md; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.git_diff.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/contributions.md
          git commit -m "MD: Auto-update contributions.md [skip ci]"
          git push
